[package]
name = "rust_cookbook"
version = "0.1.0"
authors = ["SherLzp <xiaobai084@163.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
clap = "2.33.0"
ansi_term = "0.11.0"
flate2 = "1.0.7"
tar = "0.4.22"
